# Import necessary packages
import os
import faiss
from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores import FAISS
from langchain.text_splitter import CharacterTextSplitter
from langchain.chains import RetrievalQA
from langchain_community.document_loaders import WebBaseLoader
from langchain_community.embeddings.spacy_embeddings import SpacyEmbeddings
from langchain_groq import ChatGroq
from langchain.prompts import PromptTemplate

# Initialize Groq LLM
llm = ChatGroq(model="llama-3.3-70b-versatile", api_key="")

# Load and process documents
loader = WebBaseLoader("https://python.langchain.com/docs/integrations/retrievers/")
docs = loader.load()

# Split documents into manageable chunks
text_splitter = CharacterTextSplitter(chunk_size=500, chunk_overlap=100)
documents = text_splitter.split_documents(docs)

# Choose embedding method (spaCy or OpenAI)
embedder = SpacyEmbeddings(model_name="en_core_web_md")
# embedder = OpenAIEmbeddings()  # Optional alternative

# Create FAISS vectorstore
db = FAISS.from_documents(documents, embedder)
retriever = db.as_retriever()

# Step 1: Generate Initial Answer
def generate_initial_answer(query):
    qa_chain = RetrievalQA.from_chain_type(llm=llm, retriever=retriever, chain_type="stuff")
    return qa_chain.invoke({"query": query})["result"]

# Step 2: Reflect on Answer
def reflect_on_answer(query, answer, retrieved_docs):
    context_snippets = "\n\n".join([doc.page_content for doc in retrieved_docs])
    
    prompt_template = PromptTemplate(
        input_variables=["query", "answer", "context"],
        template="""
You are an expert assistant reviewing the following answer generated by an AI model.

QUESTION: {query}

INITIAL ANSWER: {answer}

RELEVANT CONTEXT:
{context}

TASK:
- Identify any mistakes, hallucinations, or unsupported claims in the answer.
- Suggest how to improve it based on the context.

REVIEW:
"""
    )
    chain = prompt_template | llm
    return chain.invoke({"query": query, "answer": answer, "context": context_snippets})

# Step 3: Improve Answer Based on Reflection
def improve_answer(query, initial_answer, reflection):
    prompt_template = PromptTemplate(
        input_variables=["query", "initial_answer", "reflection"],
        template="""
You are an expert assistant refining an AI-generated answer based on feedback.

QUESTION: {query}

INITIAL ANSWER: {initial_answer}

REFLECTION FEEDBACK:
{reflection}

Please provide an improved answer that addresses the feedback and is well-supported by the context.
"""
    )
    chain = prompt_template | llm
    return chain.invoke({
        "query": query,
        "initial_answer": initial_answer,
        "reflection": reflection
    })

# Full Pipeline
def self_reflective_rag(query):
    initial_answer = generate_initial_answer(query)
    retrieved_docs = retriever.invoke(query)
    reflection = reflect_on_answer(query, initial_answer, retrieved_docs)
    final_answer = improve_answer(query, initial_answer, reflection)
    return {
        "initial_answer": initial_answer,
        "reflection": reflection,
        "final_answer": final_answer
    }

# Example usage
if __name__ == "__main__":
    query = "What is the mechanism of CRISPR gene editing?"
    result = self_reflective_rag(query)
    
    print("=== Initial Answer ===\n", result["initial_answer"])
    print("\n=== Reflection ===\n", result["reflection"])
    print("\n=== Final Answer ===\n", result["final_answer"])
