# Import necessary packages
import os
import faiss
from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores import FAISS
from langchain.text_splitter import CharacterTextSplitter
from langchain.chains import RetrievalQA
from langchain_community.document_loaders import WebBaseLoader
from langchain_community.embeddings.spacy_embeddings import SpacyEmbeddings
from langchain_groq import ChatGroq
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain

# Initialize Groq LLM (you already did this)
llm = ChatGroq(model="llama-3.3-70b-versatile", api_key="")

# Load documents
loader = WebBaseLoader("https://python.langchain.com/docs/integrations/retrievers/")
docs = loader.load()

# Split text
text_splitter = CharacterTextSplitter(chunk_size=500, chunk_overlap=100)
documents = text_splitter.split_documents(docs)

# Embedding with spaCy (you can replace with OpenAIEmbeddings if you prefer)
embedder = SpacyEmbeddings(model_name="en_core_web_md")
# OR you could do:
# embedder = OpenAIEmbeddings()

# Generate FAISS vectorstore
db = FAISS.from_documents(documents, embedder)
retriever = db.as_retriever()

# Step 1: Initial Answer
def generate_initial_answer(query):
    qa = RetrievalQA.from_chain_type(llm=llm, retriever=retriever, chain_type="stuff")
    return qa.run(query)

# Step 2: Reflection using Groq
def reflect_on_answer(query, answer, retrieved_docs):
    context_snippets = "\n\n".join([doc.page_content for doc in retrieved_docs])
    prompt_template = PromptTemplate(
        input_variables=["query", "answer", "context"],
        template="""
You are an expert assistant reviewing the following answer generated by an AI model.

QUESTION: {query}

INITIAL ANSWER: {answer}

RELEVANT CONTEXT:
{context}

TASK:
- Identify any mistakes, hallucinations, or unsupported claims in the answer.
- Suggest how to improve it based on the context.

REVIEW:
"""
    )
    chain = LLMChain(llm=llm, prompt=prompt_template)
    return chain.run(query=query, answer=answer, context=context_snippets)

# Step 3: Regenerate answer using reflection with Groq
def improve_answer(query, initial_answer, reflection):
    prompt_template = PromptTemplate(
        input_variables=["query", "initial_answer", "reflection"],
        template="""
You are an expert assistant refining an AI-generated answer based on feedback.

QUESTION: {query}

INITIAL ANSWER: {initial_answer}

REFLECTION FEEDBACK:
{reflection}

Please provide an improved answer that addresses the feedback and is well-supported by the context.
"""
    )
    chain = LLMChain(llm=llm, prompt=prompt_template)
    return chain.run(query=query, initial_answer=initial_answer, reflection=reflection)

# Full pipeline
def self_reflective_rag(query):
    initial_answer = generate_initial_answer(query)
    retrieved_docs = retriever.get_relevant_documents(query)
    reflection = reflect_on_answer(query, initial_answer, retrieved_docs)
    final_answer = improve_answer(query, initial_answer, reflection)
    return {
        "initial_answer": initial_answer,
        "reflection": reflection,
        "final_answer": final_answer
    }

# Example usage
result = self_reflective_rag("What is the mechanism of CRISPR gene editing?")
print("Initial Answer:\n", result["initial_answer"])
print("\nReflection:\n", result["reflection"])
print("\nFinal Answer:\n", result["final_answer"])
